#!/usr/bin/env python3
"""
Drain open community-submission PRs.

These PRs were generated by an older submission flow that appends to the
monolithic community-data.json. The current flow uses per-bundle files at
community-data/<bundleID>.json (CI regenerates community-data.json on push).

For each unique bundle ID across the open PRs, this script extracts the new
entry from the highest-numbered PR's branch, writes it to a per-bundle file,
commits + pushes to main, and closes every open submission PR with a comment.

Usage:
  scripts/merge-community-prs.py            # do it
  scripts/merge-community-prs.py --dry-run  # show what would happen
"""

import argparse
import json
import pathlib
import subprocess
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
COMMUNITY_DIR = REPO_ROOT / "community-data"
LEGACY_FILE = "community-data.json"
TITLE_PREFIX = "[Community] "
CLOSE_COMMENT = (
    "Superseded — entry merged directly via per-bundle file at "
    "`community-data/<bundle>.json`. The submission flow now writes per-bundle "
    "files which CI merges into `community-data.json` on every push to `main`. "
    "This PR targeted the legacy monolithic file and would have been overwritten "
    "by the regeneration job. Thanks for the submission!"
)


def sh(*args, capture=True, check=True):
    r = subprocess.run(args, capture_output=capture, text=True, check=check, cwd=REPO_ROOT)
    return r.stdout if capture else None


def list_prs():
    out = sh("gh", "pr", "list", "--state", "open", "--limit", "200",
            "--json", "number,title,headRefName")
    return json.loads(out)


def main_keys():
    sh("git", "fetch", "origin", "main", "--quiet")
    return set(json.loads(sh("git", "show", f"origin/main:{LEGACY_FILE}")).keys())


def extract_new_entry(pr_num, base_keys):
    sh("git", "fetch", "origin", f"pull/{pr_num}/head:pr-{pr_num}", "--quiet", "--force")
    try:
        data = json.loads(sh("git", "show", f"pr-{pr_num}:{LEGACY_FILE}"))
    except subprocess.CalledProcessError:
        return None, None
    new = set(data.keys()) - base_keys
    if len(new) != 1:
        return None, None
    k = next(iter(new))
    return k, data[k]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    prs = [p for p in list_prs() if p["title"].startswith(TITLE_PREFIX)]
    if not prs:
        print("No open community PRs.")
        return 0

    print(f"Found {len(prs)} open community PR(s).")
    base = main_keys()

    # Map bundle key -> (pr_num, entry). Keep highest PR# per key.
    by_key = {}
    pr_keys = {}  # pr_num -> key (or None)
    for pr in sorted(prs, key=lambda p: p["number"]):
        k, entry = extract_new_entry(pr["number"], base)
        pr_keys[pr["number"]] = k
        if k is None:
            print(f"  PR #{pr['number']}: could not extract a unique new key — will still close")
            continue
        by_key[k] = (pr["number"], entry)  # later (higher #) wins
        print(f"  PR #{pr['number']}: {k}")

    # Write per-bundle files for keys that don't already exist
    written = []
    skipped_existing = []
    for k, (num, entry) in sorted(by_key.items()):
        p = COMMUNITY_DIR / f"{k}.json"
        if p.exists():
            skipped_existing.append(k)
            continue
        if args.dry_run:
            print(f"  [dry-run] would write {p.relative_to(REPO_ROOT)}")
        else:
            p.write_text(json.dumps(entry, indent=2, ensure_ascii=False) + "\n")
        written.append(k)

    print()
    print(f"New per-bundle files: {len(written)}")
    print(f"Skipped (already exist): {len(skipped_existing)}")
    print(f"PRs to close: {len(prs)}")

    if args.dry_run:
        print("\nDry run — no changes made.")
        return 0

    if written:
        sh("git", "add", "community-data/")
        msg = f"Add {len(written)} community app entries from pending submission PRs"
        sh("git", "commit", "-m", msg)
        # CI regenerates community-data.json after every push, so origin/main
        # often advances between our fetch and our push. Rebase + retry once.
        try:
            sh("git", "push", "origin", "main", capture=False)
        except subprocess.CalledProcessError:
            print("Push rejected — pulling --rebase and retrying.")
            sh("git", "pull", "--rebase", "origin", "main", capture=False)
            sh("git", "push", "origin", "main", capture=False)
        print("Pushed to main.")
    else:
        print("Nothing new to commit.")

    for pr in prs:
        try:
            sh("gh", "pr", "close", str(pr["number"]), "--comment", CLOSE_COMMENT)
            print(f"Closed PR #{pr['number']}")
        except subprocess.CalledProcessError as e:
            print(f"Failed to close PR #{pr['number']}: {e}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
